/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.mobiletoly.addrbookhexktor.infra

import com.github.mobiletoly.addrbookhexktor.adapters.env.envModule
import com.github.mobiletoly.addrbookhexktor.adapters.primaryweb.webBootstrap
import com.github.mobiletoly.addrbookhexktor.coreModule
import io.ktor.server.application.Application
import io.ktor.server.application.install
import org.koin.core.logger.Level
import org.koin.ktor.plugin.Koin
import org.koin.logger.slf4jLogger

fun main(args: Array<String>) {
    return io.ktor.server.netty.EngineMain.main(args)
}

fun Application.main() {
    install(Koin) {
        slf4jLogger(level = Level.DEBUG)
        modules(
            envModule,
            coreModule,
        )
    }

    webBootstrap()
}
