/*
 * This file was generated by the Gradle 'init' task.
 */

val ktorVersion: String by rootProject
val koinVersion: String by rootProject

plugins {
    id("com.github.mobiletoly.addrbookhexktor.kotlin-application-conventions")
}

dependencies {
    api(project(":app:adapters:env"))
    api(project(":app:adapters:primary-web"))
    api(project(":app:core"))

    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.insert-koin:koin-ktor:$koinVersion")
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.mobiletoly.addrbookhexktor.infra.AppKt")
}
