openapi: 3.0.0

components:
  schemas:
    HealthResponse:
      type: object
      description: Organization info item
      required:
        - status
        - version
      properties:
        status:
          type: string
          description:
            overall system health
        version:
          type: string
          description:
            build version
        remoteService:
          type: string
          description:
            address book remote service health
        database:
          type: string
          description:
            database health
